import os, re, yaml, shutil
import numpy as np
from .structures import Structure
from .math import diagonalQ
from .VaspBandUnfolding import vaspwfc
from .VaspBandUnfolding.unfold import find_K_from_k, make_kpath, removeDuplicateKpoints, unfold
from .io import get_structure, get_kpoints, get_incar, show_incar, get_potcar
from .bands import clean_kpath, get_band_indices
from pymatgen.io.vasp.inputs import Kpoints



# Unfolding
def find_supercell_matrix(primitive_structure: Structure, supercell_structure: Structure, verbose: bool = True) -> tuple[np.ndarray, np.ndarray]:
    """
    Compares a supercell structure with a primitive structure and returns the transformation matrix needed to generate a supercell from the primitive structure that has the same size as the ssupercell structure

    Args:
        primitive_structure (Initio.Structure): Primitive structure
        supercell_structure (Initio.Structure): Supercell structure
        verbose (bool, optional): Whether or not to print the transformation matrix to terminal. Defaults to True.

    Returns:
        tuple[np.ndarray, np.ndarray]: The first element is the rounded transformation matrix with integer entries. The second one is the raw transformation matrix with float entries.
    """
    try:
        prim_vecs = primitive_structure.lattice.matrix
        supercell_vecs = supercell_structure.lattice.matrix
        raw_transformation_matrix = np.dot(supercell_vecs, np.linalg.inv(prim_vecs))
        transformation_matrix = np.astype(np.round(raw_transformation_matrix), int)
        
        if verbose: print(f"{transformation_matrix = }\n{raw_transformation_matrix = }")
        return transformation_matrix, raw_transformation_matrix
    except:
        return np.zeros((3, 3)), np.zeros((3, 3))

def analyze_supercell_linearity(primitive_structure: Structure, supercell_structure: Structure, verbose: bool = True) -> tuple[bool, list[int], list[int]]:
    """
    Analyzes whether the supercell structure can be generated by linearly copying the primitive structure along its lattice vectors.
    If False, 

    Args:
        primitive_structure (Initio.Structure): Primitive structure.
        supercell_structure (Initio.Structure): Supercell structure.
        verbose (bool, optional): Whether to print the information to terminal. Defaults to True.

    Returns:
        tuple[bool, list[int], int]: Whether the supercell is linear (bool), what the axes are along which the primitive cell is copied (list of integers), how many copies along each lattice vector (integer).
    """
    transformation_matrix, raw_transformation_matrix = find_supercell_matrix(primitive_structure, supercell_structure, verbose = False)
    supercell_copies = [int(value) for value in np.diag(transformation_matrix)]
    supercell_is_linear = diagonalQ(transformation_matrix) # Is the transformation linear (i.e. simply copied along the primitive cell directions without mixing to change the shape of the cell)?
    supercell_axes: list[int] = [4] # Axis or axes along which the primitive cell was copied. [4] is a dummy (fallback) value.
    
    if supercell_is_linear:
        [x_copies, y_copies, z_copies] = supercell_copies
        
        if x_copies > 1 and y_copies + z_copies < 3: supercell_axes = [0] # x axis
        elif y_copies > 1 and x_copies + z_copies < 3: supercell_axes = [1] # y axis
        elif z_copies > 1 and x_copies + y_copies < 3: supercell_axes = [2] # z axis
        elif x_copies > 1 and y_copies > 1 and z_copies < 1: supercell_axes = [0, 1] # xy plane
        else: supercell_axes = [4, 5] # Not yet implemented
        if verbose: print(f"{supercell_is_linear = }; {supercell_axes = }; {supercell_copies = }")
    else:
        if verbose: print(f"{supercell_is_linear = }; Supercell axes and copies not well-defined.")
    return supercell_is_linear, supercell_axes, supercell_copies

def generate_k_mapping(transformation_matrix: np.ndarray = np.eye(3), kpath: list | np.ndarray = [], crystal_type: str = "hexagonal", nseg: int = 12) -> tuple[np.ndarray, np.ndarray]:
    """
    Generate K-points of the supercell Brillouin zone where the band structure should be sampled in order to have the band structure fold back properly onto the k-points of the primitive cell.

    Args:
        transformation_matrix (np.ndarray, optional): Supercell transformation matrix. Defaults to np.eye(3).
        kpath (list | np.ndarray, optional): k-points of the primitive cell. Defaults to [].
        crystal_type (str, optional): Crystal type. Defaults to "hexagonal".
        nseg (int, optional): Resolution. Defaults to 12.

    Returns:
        tuple[np.ndarray, np.ndarray]: k-points of the supercell, and a mapping from K to k
    """
    k_path_fractional = clean_kpath(kpath = kpath, crystal_type = crystal_type)

    kpts_prim = make_kpath(k_path_fractional, nseg = nseg) # Structure of the KPOINTS as required by the VASPbandunfolding library
    K_in_sup = []
    for k in kpts_prim:
        K, G = find_K_from_k(k, transformation_matrix)
        K_in_sup.append(K)
    reduced_K, k_map = removeDuplicateKpoints(K_in_sup, return_map = True)
    return reduced_K, k_map

def test_k_mappings(transformation_matrix: np.ndarray, kpath: list | np.ndarray = [], crystal_type: str = "", npoints_max: int = 40):
    lengths = []
    npoints = []
    for n in range(npoints_max):
        reduced_K, k_map = generate_k_mapping(transformation_matrix, kpath = kpath, crystal_type = crystal_type, nseg = n)
        lengths.append(len(k_map))
        npoints.append(n)
    return (npoints, lengths)

def generate_unfolding_calculation(self, supercell_folder: str | None = None, primitive_folder: str | None = None, kpath: list | np.ndarray = ["gamma", "k", "m", "gamma"], crystal_type: str = "hexagonal", nseg: int = 12, suppress: bool = False) -> None:
    try:
        if not isinstance(supercell_folder, str) or not os.path.isdir(supercell_folder):
            raise Exception("Invalid supercell calculation folder")
        if not isinstance(primitive_folder, str) or not os.path.isdir(primitive_folder):
            raise Exception("Invalid primitive calculation folder")
        
        
        
        # Create the 'scf' and 'unfolding' folders and copy the structures
        contcar_file = os.path.join(supercell_folder, "CONTCAR")
        if not os.path.isfile(contcar_file):
            raise Exception("No valid CONTCAR file found of the supercell")
        
        supercell_struc = get_structure(contcar_file)
        scf_folder = os.path.join(supercell_folder, "scf")
        unfolding_folder = os.path.join(supercell_folder, "unfolding")
        
        if not suppress:
            if not os.path.isdir(scf_folder): os.mkdir(scf_folder) # Create the SCF folder
            supercell_struc.to_file(os.path.join(scf_folder, "POSCAR"))
            
            if not os.path.isdir(unfolding_folder): os.mkdir(unfolding_folder) # Create the unfolding folder            
            supercell_struc.to_file(os.path.join(unfolding_folder, "POSCAR"))

        
        
        # Retrieve the supercell transformation matrix from the supercell structure and the primitive cell structure
        contcar_file = os.path.join(primitive_folder, "CONTCAR")
        if not os.path.isfile(contcar_file):
            raise Exception("No valid CONTCAR file found of the primitive cell")
        
        prim_struc: Structure = get_structure(contcar_file)
        transformation_matrix, transformation_matrix_raw = find_supercell_matrix(prim_struc, supercell_struc)
        print("\nI found the following transformation matrix from primitive to supercell:\n")
        print(f"{transformation_matrix_raw}")
        
        
        
        # Get the INCAR from the supercell calculation            
        supercell_incar = get_incar(os.path.join(supercell_folder, "INCAR"))            
        print("\nI found the following INCAR parameters for the supercell calculation:\n")
        show_incar(supercell_incar)
        
        # Adapt the INCAR for the single-point SCF calculation and subsequent unfolding calculation
        supercell_incar["LCHARG"] = True
        supercell_incar["LORBIT"] = False
        supercell_incar["LWAVE"] = False # Do not generate a WAVECAR at this time. Instead, use the Eigenvalues to parse which bands to use later and generate the WAVECAR only at the unfolding stage.
        supercell_incar["NSW"] = 0
        supercell_incar["IBRION"] = -1
        if not suppress: supercell_incar.write_file(os.path.join(scf_folder, "INCAR"))

        supercell_incar["LCHARG"] = False
        supercell_incar["ICHARG"] = 11
        supercell_incar["LORBIT"] = 11
        supercell_incar["LWAVE"] = True            
        if not suppress:
            supercell_incar.write_file(os.path.join(unfolding_folder, "INCAR"))
            print("\nSingle-point SCF calculation INCAR file written to 'scf' directory, and NSCF calculation INCAR written to 'unfolding' directory.\n")
        
        
        
        # Copy the POTCARs
        potcar_file = os.path.join(supercell_folder, "POTCAR")
        if not os.path.isfile(potcar_file):
            raise Exception("Missing POTCAR")
        supercell_potcar = get_potcar(potcar_file)
        if not suppress:
            supercell_potcar.write_file(os.path.join(scf_folder, "POTCAR"))
            supercell_potcar.write_file(os.path.join(unfolding_folder, "POTCAR"))


        
        # Create the KPOINTS files
        kpoints_file = os.path.join(supercell_folder, "KPOINTS")
        if os.path.isfile(kpoints_file):
            supercell_kpoints = get_kpoints(kpoints_file)
        else: # No KPOINTS found: fall back to generating a gamma-point calculation
            print("No KPOINTS found in supercell calculation.\nFalling back to generating a gamma-point calculation file")
            supercell_kpoints = Kpoints.gamma_automatic()
        if not suppress: supercell_kpoints.write_file(os.path.join(scf_folder, "KPOINTS"))
        
        kpath = clean_kpath(kpath, crystal_type = crystal_type)            
        reduced_K, k_map = generate_k_mapping(transformation_matrix, kpath = kpath, crystal_type = crystal_type, nseg = nseg)            
        kpts_prim = make_kpath(kpath, nseg = nseg) # Structure of the KPOINTS as required by the VASPbandunfolding library
        K_in_sup = []
        for k in kpts_prim:
            K, G = find_K_from_k(k, transformation_matrix)
            K_in_sup.append(K)
        reduced_K, k_map = removeDuplicateKpoints(K_in_sup, return_map = True)
        weights = [1] * len(reduced_K)
        
        kpoints_obj = Kpoints(comment = "Unfolding supercell k-points generated via VaspBandUnfolding and Initio", num_kpts = len(reduced_K), style = Kpoints.supported_modes.Reciprocal, kpts = reduced_K, kpts_weights = weights)
        if not suppress: kpoints_obj.write_file(os.path.join(unfolding_folder, "KPOINTS"))
        
        if not suppress:
            with open(os.path.join(unfolding_folder, "unfolding_parameters.yml"), "w") as f:
                yaml.safe_dump({"transformation_matrix": transformation_matrix.tolist(), "k_map": k_map.tolist()}, f)
        
        if not suppress:
            print("\nI found the structure and POTCAR of the supercell calculation and copied them to the new folders 'scf' and 'unfolding'.")
            print("Please submit the job in the 'scf' folder to VASP first.")
            print("When completed, run Initio.scf_to_unfolding to finish setting up the 'unfolding' folder for the band unfolding calculation.")
        
    except Exception as e:
        print(f"Error encountered while generating an unfolding calculation: {e}")
    
    return

def scf_to_unfolding(supercell_folder: str | None = None) -> None:
    if not isinstance(supercell_folder, str) or not os.path.isdir(supercell_folder): raise IOError("Invalid supercell calculation folder")
    
    scf_folder = os.path.join(supercell_folder, "scf")
    unfolding_folder = os.path.join(supercell_folder, "unfolding")
    if not os.path.isdir(scf_folder): raise IOError("'scf' folder not found")
    if not os.path.isdir(unfolding_folder): raise IOError("'unfolding' folder not found")
    
    try:
        E_Fermi, min_band, max_band = get_band_indices(scf_folder, energy_range = [-1.6, 1.6])
        print(f"{min_band = }, {max_band = }")
        
        chgcar_path = os.path.join(scf_folder, "CHGCAR")
        chgcar_destination = os.path.join(unfolding_folder, "CHGCAR")

        if os.path.isfile(chgcar_path): shutil.copy(chgcar_path, chgcar_destination)
        else: raise Exception("No CHGCAR found in the 'scf' folder")
    except Exception as e:
        print(f"Error encountered while running initio.scf_to_unfolding: {e}")        
    return



def gaussian_smearing_org(x, x0, sigma = 0.05):
    '''
    Gaussian smearing of a Delta function.
    '''
    return 1. / (np.sqrt(2 * np.pi) * sigma) * np.exp(-(x - x0) ** 2 / (2 * sigma ** 2))

def string2index(string):
    if ':' not in string:
        raise ValueError("Invalid slice string!")
    i = []
    for s in string.split(':'):
        if s == '':
            i.append(None)
        else:
            i.append(int(s))
    i += (3 - len(i)) * [None]
    return slice(*i)

def gradient_fill(x, y, fill_color = None, ax = None, direction = 1, **kwargs):
    """
    Plot a line with a linear alpha gradient filled beneath it.

    Parameters
    ----------
    x, y : array-like
        The data values of the line.
    fill_color : a matplotlib color specifier (string, tuple) or None
        The color for the fill. If None, the color of the line will be used.
    ax : a matplotlib Axes instance
        The axes to plot on. If None, the current pyplot axes will be used.
    Additional arguments are passed on to matplotlib's ``plot`` function.

    Returns
    -------
    line : a Line2D instance
        The line plotted.
    im : an AxesImage instance
        The transparent gradient clipped to just the area beneath the curve.
    """

    import matplotlib.colors as mcolors
    from matplotlib.patches import Polygon

    line, = ax.plot(x, y, **kwargs)
    if fill_color is None:
        fill_color = line.get_color()

    # print fill_color
    zorder = line.get_zorder()
    alpha = line.get_alpha()
    alpha = 1.0 if alpha is None else alpha

    z = np.empty((100, 1, 4), dtype=float)
    rgb = mcolors.colorConverter.to_rgb(fill_color)
    z[:, :, :3] = rgb
    if direction == 1:
        z[:, :, -1] = np.linspace(0, alpha, 100)[:, None]
    else:
        z[:, :, -1] = np.linspace(alpha, 0, 100)[:, None]

    xmin, xmax, ymin, ymax = x.min(), x.max(), y.min(), y.max()
    im = ax.imshow(z, aspect='auto', extent=[xmin, xmax, ymin, ymax],
                   origin='lower', zorder=zorder)

    xy = np.column_stack([x, y])
    if direction == 1:
        xy = np.vstack([[xmin, ymin], xy, [xmax, ymin], [xmin, ymin]])
    else:
        xy = np.vstack([[xmin, ymax], xy, [xmax, ymax], [xmin, ymax]])
    clip_path = Polygon(xy, lw=0.0, facecolor='none',
                        edgecolor='none', closed=True)
    ax.add_patch(clip_path)
    im.set_clip_path(clip_path)

    ax.autoscale(True)
    return line, im



class UnfoldProcar(object):
    '''
    A class for dealing with VASP PROCAR file.
    '''

    def __init__(self, inf = "PROCAR", lsoc = False):
        '''
        Initialization
        '''

        self._fname = inf
        # the directory containing the input file
        self._dname = os.path.dirname(inf)
        if self._dname == '':
            self._dname = '.'

        self._lsoc = lsoc

        try:
            self._procar = open(self._fname, 'r')
        except:
            raise IOError('Failed to open %s' % self._fname)

        self.readProcar()

        # parameters usefull for dos generation
        self._sigma = 0.05
        self._nedos = 3000
        # Total DOS for each KS energy, with shape (NSPIN, NKPTS, NBANDS, NEDOS)
        self._tdos = None
        # Total DOS with shape (NSPIN, NEDOS)
        self._totalDOS = None

        self._spd_index = {
            's': 0,
            'py': 1, 'pz': 2, 'px': 3,
            'dxy': 4, 'dyz': 5, 'dz2': 6, 'dxz': 7, 'dx2': 8
        }

        # the basis vectors of the cell
        self._cell = None
        self._kpath = None

    def readProcar(self):
        '''
        Extract the info from PROCAR.
        '''

        inp = [line for line in self._procar if line.strip()]

        # when the band number is too large, there will be no space between ";" and
        # the actual band number. A bug found by Homlee Guo.
        # Here, #kpts, #bands and #ions are all integers
        self._nkpts, self._nbands, self._nions = [
            int(xx) for xx in re.sub('[^0-9]', ' ', inp[1]).split()]

        # band projectron on each atoms or s/p/d orbitals
        self._aproj = np.asarray([line.split()[1:-1] for line in inp
                                  if not re.search('[a-zA-Z]', line)],
                                 dtype=float)
        # k-points weights of each k-points
        # self._kptw = np.asarray([line.split()[-1]
        # In case that there are no blank spaces before the '-' sign of the
        # k-points coordinates
        self._kptw = np.asarray([re.sub(r'(\d)-', r'\1 -', line).split()[-1]
                                 for line in inp if 'weight' in line], dtype=float)
        # k-points vectors of each k-points
        # self._kptv = np.asarray([line.split()[-6:-3]
        # In case that there are no blank spaces before the '-' sign of the
        # k-points coordinates
        self._kptv = np.asarray([re.sub(r'(\d)-', r'\1 -', line).split()[-6:-3]
                                 for line in inp if 'weight' in line], dtype=float)
        # in case of spin poliarized calculation
        self._kptv = self._kptv[:self._nkpts]
        # band energies
        self._eband = np.asarray([line.split()[-4] for line in inp
                                  if 'occ.' in line], dtype=float)

        self._nlmax = self._aproj.shape[-1]
        self._nspin = self._aproj.shape[0] // (
            self._nkpts * self._nbands * self._nions)
        self._nspin //= 4 if self._lsoc else 1

        if self._lsoc:
            self._aproj.resize(self._nspin, self._nkpts,
                               self._nbands, 4, self._nions, self._nlmax)
            self._Mxyz = self._aproj[:, :, :, 1:, :, :]
            self._aproj = self._aproj[:, :, :, 0, :, :]
        else:
            self._aproj.resize(self._nspin, self._nkpts,
                               self._nbands, self._nions, self._nlmax)

        self._kptw.shape = (self._nspin, self._nkpts)
        self._kptw_org = self._kptw.copy()
        self._eband.shape = (self._nspin, self._nkpts, self._nbands)

        # close the PROCAR
        self._procar.close()

    def get_magnetization(self):
        '''
        In an noncollinear calculation, get the magnetization in x/y/z
        direction.
        '''

        assert self._lsoc

        return self._Mxyz.copy()

    def get_nkpts(self):
        '''
        get number of kpoints.
        '''
        return self._nkpts

    def get_nspin(self):
        '''
        get number of spin
        '''
        return self._nspin

    def get_nbands(self):
        '''
        get number of bands
        '''
        return self._nbands

    def get_band_energies(self):
        '''
        Return the band energies
        '''
        return self._eband.copy()

    def get_kpath(self, cell = None, nkseg = None):
        '''
        Construct k-point path, find out the k-path boundary if possible.
        '''

        if self._kpath is None:
            if self._cell is None:
                if cell is None:
                    try:
                        self._cell = read(
                            self._dname + '/POSCAR', format='vasp').cell.copy()
                    except:
                        raise ValueError(
                            'Error in reading cell info from POSCAR!')
                else:
                    self._cell = np.array(cell, dtype=float)
                    assert self._cell.shape == (3, 3)

            if nkseg is None:
                if os.path.isfile(self._dname + "/KPOINTS"):
                    kfile = open(self._dname + "/KPOINTS").readlines()
                    if kfile[2][0].upper() == 'L':
                        nkseg = int(kfile[1].split()[0])
                    else:
                        raise ValueError(
                            'Error reading number of k-points from KPOINTS')

            assert isinstance(nkseg, int) and nkseg > 0

            nsec = self._nkpts // nkseg
            icell = np.linalg.inv(self._cell).T

            # vkpts_d = np.diff(self._kptv, axis=0)
            # self._kpath     = np.zeros(self._nkpts, dtype=float)
            # self._kpath[1:] = np.cumsum(np.linalg.norm(np.dot(vkpts_d, icell), axis=1))

            v = self._kptv.copy()
            for ii in range(nsec):
                ki = ii * nkseg
                kj = (ii + 1) * nkseg
                v[ki:kj, :] -= v[ki]

            self._kpath = np.linalg.norm(np.dot(v, icell), axis=1)
            for ii in range(1, nsec):
                ki = ii * nkseg
                kj = (ii + 1) * nkseg
                self._kpath[ki:kj] += self._kpath[ki - 1]

            self._kbound = np.concatenate(
                (self._kpath[0::nkseg], [self._kpath[-1], ]))

        return self._kpath, self._kbound

    def isSoc(self):
        return True if self._lsoc else False

    def get_sigma(self):
        '''
        return dos brodening parameter
        '''
        return self._sigma

    def set_sigma(self, sigma):
        '''
        set dos brodening parameter
        '''
        self._sigma = sigma

        # re-generate the DOS with the new SIGMA
        if self._tdos is not None:
            if not np.isclose(sigma, self._sigma):
                self.init_dos()

    def get_nedos(self):
        return self._nedos

    def set_nedos(self, nedos):
        '''
        set number of point in smooth DOS
        '''
        assert isinstance(nedos, int), 'NEDOS shoule be int!'
        self._nedos = nedos

        # re-generate the DOS with the new NEDOS
        if self._tdos is not None:
            if self._nedos != nedos:
                self.init_dos()

    def get_kpts_weight(self):
        '''
        return the k-points weights
        '''
        return self._kptw.copy()

    def set_kpts_weight(self, kptw):
        '''
        set the k-points weights
        '''
        kptw = np.array(kptw)
        assert kptw.shape == self._kptw.shape
        self._kptw = kptw

        # re-generate the DOS with the new kptw
        if self._tdos is not None:
            self.init_dos()

    def restore_kpts_weight(self, kptw):
        '''
        set the k-points weights
        '''
        self._kptw = self._kptw_org.copy()

        # re-generate the DOS with the new kptw
        if self._tdos is not None:
            self.init_dos()

    def init_dos(self):
        '''
        dos initialization
        '''

        # print 'calculating dos'
        emin = self._eband.min()
        emax = self._eband.max()
        eran = emax - emin
        emin = emin - eran * 0.05
        emax = emax + eran * 0.05

        self._xen = np.linspace(emin, emax, self._nedos)
        self._tdos = np.empty(
            (self._nspin, self._nkpts, self._nbands, self._nedos))

        for ispin in range(self._nspin):
            sign = 1 if ispin == 0 else -1
            for ikpt in range(self._nkpts):
                for iband in range(self._nbands):
                    x0 = self._eband[ispin, ikpt, iband]
                    self._tdos[ispin, ikpt, iband] = sign * self._kptw[ispin, ikpt] \
                        * gaussian_smearing_org(self._xen, x0, self._sigma)\

    def translate_selection(self, atoms = ':', kpts = ':', spd = ':'):
        '''
        '''
        # string is Iterable too
        assert (isinstance(atoms, int)
                or isinstance(atoms, Iterable)
                or isinstance(atoms, str))
        assert (isinstance(kpts, int)
                or isinstance(kpts, Iterable)
                or isinstance(kpts, str))
        assert (isinstance(spd, int)
                or isinstance(spd, Iterable)
                or isinstance(kpts, str))

        if isinstance(atoms, int):
            atoms = [atoms]
        if isinstance(kpts, int):
            kpts = [kpts]
        if isinstance(spd, int):
            spd = [spd]

        if isinstance(atoms, str):
            atoms = string2index(atoms)
        if isinstance(kpts, str):
            kpts = string2index(kpts)
        if isinstance(spd, str):
            spd = string2index(spd)

        # remove duplicate selections
        if isinstance(atoms, Iterable):
            atoms = list(set(atoms))
        if isinstance(kpts, Iterable):
            kpts = list(set(kpts))
        if isinstance(spd, Iterable):
            spd = [ii if isinstance(ii, int) else self._spd_index[ii]
                   for ii in spd]
            spd = list(set(spd))

        return atoms, kpts, spd

    def get_proj(self):
        '''
        get the partial weight.
        '''
        return self._aproj.copy()

    def get_total_dos(self):
        '''
        The total DOS
        '''
        if self._tdos is None:
            self.init_dos()

        if self._totalDOS is None:
            self._totalDOS = np.sum(self._tdos, axis=(1, 2))

        return self._xen, self._totalDOS

    def get_pw(self, atoms = ':', kpts = ':', spd = ':'):
        '''
        Get site/k-points/spd-orbital projected weight for each KS orbital.

        atoms : selected atoms index.
                Valid values:
                    ":"       -> for all atoms
                    "0::2"    -> for even index atoms
                    [0, 1, 2] -> atom indices specified by list
                    0         -> atom indices specified by integer

        kpts  : selected k-points index
                Valid values:
                    ":"       -> for all k-points
                    "0::2"    -> for even index k-points
                    [0, 1, 2] -> k-points indices specified by list
                    0         -> k-points indices specified by integer

        spd   : selected s/p/d-orbitals, the s/p/d-orbital and the corresponding
                index are:
                    's' : 0,
                    'py' : 1, 'pz' : 2, 'px' : 3,
                    'dxy' : 4, 'dyz' : 5, 'dz2' : 6, 'dxz' : 7, 'dx2' : 8

                Valid values:
                    ":"         -> for all s/p/d-orbitals
                    "0::2"      -> for even index
                    [0, 1, 2]   -> s/p/d-orbitals specified by list of integer
                    ['s', 'py'] -> s/p/d-orbitals specified by list of names
                    0           -> s/p/d-orbitals indices specified by integer
        '''

        atoms, kpts, spd = self.translate_selection(atoms, kpts, spd)

        # problem with mixed advanced indexing and basic indexing, see scipy
        # documents for reference
        # https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#combining-advanced-and-basic-indexing
        #
        # a=np.zeros((2,3,4)); b=np.ones((3,4)); I=np.array([0,1])
        # b[:,I].shape = (3, 2)
        # a[0,:,I].shape = (2, 3)

        # Consider indexing a 3D array arr with shape (X, Y, Z):
        #
        # arr[:, [0, 1], 0] has shape (X, 2).
        # arr[[0, 1], 0, :] has shape (2, Z).
        # arr[0, :, [0, 1]] has shape (2, Y), not (Y, 2)

        pw = []
        for ispin in range(self._nspin):
            p0 = self._aproj[ispin, kpts]
            # sum over the s/p/d projection
            p0 = np.sum(p0[..., spd],   axis=-1)
            # sum over the site projection
            p0 = np.sum(p0[..., atoms], axis=-1)

            pw.append(p0)

        return np.array(pw, dtype=float)

    def get_pdos(self, atoms = ':', kpts = ':', spd = ':'):
        '''
        Get site/k-points/spd-orbital projected partial density of states (PDOS)
        '''

        if self._tdos is None:
            self.init_dos()

        pdos = []
        proj = self.get_pw(atoms, kpts, spd)

        atoms, kpts, spd = self.translate_selection(atoms, kpts, spd)

        if len(np.arange(self._nkpts)[kpts]) == self._nkpts:
            if np.all(
                np.sort(np.arange(self._nkpts)[kpts]) == np.arange(self._nkpts)
            ):
                used_all_kpts = True
            else:
                used_all_kpts = False
        else:
            used_all_kpts = False

        for ispin in range(self._nspin):
            pw = proj[ispin]

            if used_all_kpts:
                td = self._tdos[ispin, kpts]
            else:
                # if not all the k-points are used, then probably we should get
                # rid of the k-point weights
                td = self._tdos[ispin, kpts, ...] / \
                    self._kptw[ispin, kpts, np.newaxis, np.newaxis]

            pdos.append(np.sum(pw[..., np.newaxis] * td, axis=(0, 1)))

            # pwht = np.sum(self._aproj[ispin][kpts,:,atoms,spd], axis=(-1, -2))
            # pdos.append(np.sum(pwht[..., np.newaxis] * self._tdos[ispin][kpts,...], axis=(0, 1)))

        # only return one dos if not spin-polarized
        # p = pdos[0] if self._nspin == 1 else pdos
        pdos = np.array(pdos, dtype=float)

        return self._xen, pdos

    def get_pband(self, atoms = ':', kpts = ':', spd = ':', cell = None, nkseg = None):
        '''
        Construct the band structure from PROCAR. In addition, the
        site/k-points/spd-orbital projection of each KS orbital will be
        returned.
        '''

        k, b = self.get_kpath(cell, nkseg)
        e = self.get_band_energies()
        w = self.get_pw(atoms, kpts, spd)

        return k, b, e, w

